// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUoCM_8WP-Z7o0w9F-dRZsUYbyFg7YuO0',
    appId: '1:482276707475:web:2f422d12c97df492d41166',
    messagingSenderId: '482276707475',
    projectId: 'open-mic-5cc8e',
    authDomain: 'open-mic-5cc8e.firebaseapp.com',
    storageBucket: 'open-mic-5cc8e.appspot.com',
    measurementId: 'G-L698D8LZLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCINNQs4kndPX8k7qhUAFX24OA9G6RNBKk',
    appId: '1:482276707475:android:85c5c6e9656fc4b2d41166',
    messagingSenderId: '482276707475',
    projectId: 'open-mic-5cc8e',
    storageBucket: 'open-mic-5cc8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyjAjlCQ3hI_rrNlpNV4D-qCKumU8qm-0',
    appId: '1:482276707475:ios:ebdecf6627457b46d41166',
    messagingSenderId: '482276707475',
    projectId: 'open-mic-5cc8e',
    storageBucket: 'open-mic-5cc8e.appspot.com',
    iosBundleId: 'com.M3.Open-Mic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyjAjlCQ3hI_rrNlpNV4D-qCKumU8qm-0',
    appId: '1:482276707475:ios:a308bb7c110a810cd41166',
    messagingSenderId: '482276707475',
    projectId: 'open-mic-5cc8e',
    storageBucket: 'open-mic-5cc8e.appspot.com',
    iosBundleId: 'com.M3.Open-Mic.RunnerTests',
  );
}
