#!/bin/bash

echo "🚀 Setting up GitHub Pages for OpenSlot Support"
echo "================================================"

echo ""
echo "📋 Instructions to follow:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Create a new repository called: openslot-support"
echo "3. Make it PUBLIC (required for free GitHub Pages)"
echo "4. Don't initialize with README (we'll upload our files)"
echo "5. Click 'Create repository'"
echo ""
echo "6. After creating the repository, run these commands:"
echo "   cd /tmp/openslot-support"
echo "   git remote add origin https://github.com/YOUR_USERNAME/openslot-support.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "7. Enable GitHub Pages:"
echo "   - Go to your repository Settings"
echo "   - Scroll down to 'Pages' section"
echo "   - Under 'Source', select 'Deploy from a branch'"
echo "   - Choose 'main' branch and '/ (root)' folder"
echo "   - Click 'Save'"
echo ""
echo "8. Your support page will be available at:"
echo "   https://YOUR_USERNAME.github.io/openslot-support/"
echo ""
echo "9. Update your app's support URL to:"
echo "   https://YOUR_USERNAME.github.io/openslot-support/"
echo ""

echo "📁 Files ready in /tmp/openslot-support/:"
ls -la /tmp/openslot-support/

echo ""
echo "✅ Ready to upload to GitHub!"
echo ""
echo "Would you like me to help you with any of these steps?" 